### ISSUE TITLE
Invalid version...

### ISSUE THREAD

**Issue by mrlook2** [mgejke/hass-sectoralarm#25]
Is this broken? I cant get it to work. I have the following in my configuration.yaml:
Using Home assistant 0.98.2

sector_alarm:
  email: xxx@xxx.com
  password: Mysecret
  alarm_id: "12345678"

But I'm getting the following in the log:

2019-10-09 08:58:42 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sector_alarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-10-09 08:58:47 ERROR (MainThread) [homeassistant.setup] Error during setup of component sector_alarm
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/home/homeassistant/.homeassistant/custom_components/sector_alarm/__init__.py", line 71, in async_setup
    await sector_data.update()
  File "/home/homeassistant/.homeassistant/custom_components/sector_alarm/__init__.py", line 130, in update
    *[task() for task in self._update_tasks])
  File "/home/homeassistant/.homeassistant/custom_components/sector_alarm/__init__.py", line 153, in _update_temperatures
    temperatures = await self._async_sector.get_temperatures()
  File "/srv/homeassistant/lib/python3.6/site-packages/asyncsector/asyncsector.py", line 76, in get_temperatures
    return await get_json(request)
  File "/srv/homeassistant/lib/python3.6/site-packages/asyncsector/util.py", line 19, in get_json
    raise Exception("Error from api: %s" % result)
Exception: Error from api: "INVALID_VERSION"

Also tried with the 
version: 'v1_1_70' 
but still the same issue

**Comment by plastfuglen** [comment]
Have you tried to set the version to 'v1_1_73'?

**Comment by mrlook2** [comment]
I can see something with v1_1_74 and that seemes to be wotking, thank you

**Comment by mgejke** [comment]
Updated to use the v1_1_76 as version, but it's now also possible to use 'auto' which hopefully should fetch the correct version and use that.
