### ISSUE TITLE
Error with Hass.io version 0.103

### ISSUE THREAD

**Issue by linusmasser** [mgejke/hass-sectoralarm#26]
After upgrading to Hass.io 0.103 this does not work. See error message below:

```
Error while setting up platform sector_alarm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/sector_alarm/alarm_control_panel.py", line 25, in async_setup_platform
    async_add_entities([SectorAlarmPanel(sector_hub, code, code_format)])
TypeError: Can't instantiate abstract class SectorAlarmPanel with abstract methods supported_features
```

**Comment by axlthorell** [comment]
Just added PR #27 , give it a try.

**Comment by linusmasser** [comment]
It seems to work now!
I can arm and disarm from HA.

**Comment by PalmMx** [comment]
Great work @axlthorell

**Comment by mgejke** [comment]
PR #27 merged!
