### ISSUE TITLE
Error loading with Hass 0.81.2

### ISSUE THREAD

**Issue by Dankar82** [mgejke/hass-sectoralarm#7]
Error while loading the component.

Home Assistant
0.81.2

2018-11-01 17:53:49 ERROR (MainThread) [homeassistant.setup] Error during setup of component sector_alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/root/.homeassistant/custom_components/sector_alarm.py", line 82, in async_setup
    CONF_CODE: config[DOMAIN][CONF_CODE]
TypeError: load_platform() missing 1 required positional argument: 'hass_config'

**Comment by tomoqv** [comment]
I am having the same problem:

```
2018-11-01 20:25:57 ERROR (MainThread) [homeassistant.setup] Error during setup of component sector_alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/sector_alarm.py", line 77, in async_setup
    load_platform(hass, 'sensor', DOMAIN)

```

**Comment by mgejke** [comment]
Downgrade to 0.81.1 for now, will fix as soon as possible!

**Comment by endor-force** [comment]
Fix provided, waiting for approval by @mgejke  
https://github.com/mgejke/hass-sectoralarm/pull/8

**Comment by mgejke** [comment]
Merged, thanks!
