### ISSUE TITLE
Loads of errors when starting Home assistant v0.88.0

### ISSUE THREAD

**Issue by phellarv** [mgejke/hass-sectoralarm#9]
2019-02-20 23:35:21 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sector_alarm.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sector_alarm.sensor'; 'custom_components.sector_alarm' is not a package
2019-02-20 23:35:21 WARNING (MainThread) [homeassistant.loader] You are using a custom component for sensor.sector_alarm which has not been tested by Home Assistant. This component might cause stability problems
, be sure to disable it if you do experience issues with Home Assistant.
2019-02-20 23:35:21 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change sensor/sector_alarm.py to sector_alarm/sensor.py. This will stop working soon.
2019-02-20 23:35:21 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sector_alarm.alarm_control_panel. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sector_alarm.alarm_control_panel'; 'custom_components.sector_alarm' is not a package
2019-02-20 23:35:21 WARNING (MainThread) [homeassistant.loader] You are using a custom component for alarm_control_panel.sector_alarm which has not been tested by Home Assistant. This component might cause stabi
lity problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-20 23:35:21 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change alarm_control_panel/sector_alarm.py to sector_alarm/alarm_control_panel.py. This will stop work
ing soon.
2019-02-20 23:36:42 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sector_alarm.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sector_alarm.sensor'; 'custom_components.sector_alarm' is not a package
2019-02-20 23:36:42 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change sensor/sector_alarm.py to sector_alarm/sensor.py. This will stop working soon.
2019-02-20 23:36:44 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sector_alarm.alarm_control_panel. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sector_alarm.alarm_control_panel'; 'custom_components.sector_alarm' is not a package
2019-02-20 23:36:44 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change alarm_control_panel/sector_alarm.py to sector_alarm/alarm_control_panel.py. This will stop work
ing soon.
2019-02-20 23:36:46 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sector_alarm.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sector_alarm.sensor'; 'custom_components.sector_alarm' is not a package
2019-02-20 23:36:46 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change sensor/sector_alarm.py to sector_alarm/sensor.py. This will stop working soon.
2019-02-20 23:36:46 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sector_alarm.alarm_control_panel. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sector_alarm.alarm_control_panel'; 'custom_components.sector_alarm' is not a package
2019-02-20 23:36:46 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change alarm_control_panel/sector_alarm.py to sector_alarm/alarm_control_panel.py. This will stop work
ing soon.

**Comment by phellarv** [comment]
https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

**Comment by haqwin** [comment]
I found this post that explains the new structure for sector_alamr
https://community.home-assistant.io/t/sector-alarm/24712/100

> 1. create new folder custom_components\sector_alarm
> 2. Move custom_components\sector_alarm.py to custom_components\sector_alarm\__init__.py
> 3. Move custom_components\sensor\sector_alarm.py to custom_components\sector_alarm\sensor.py
> 4. Move custom_components\alarm_control_panel\sector_alarm.py to custom_components\sector_alarm\alarm_control_panel.py

this works for me at least

**Comment by Rawet** [comment]
> I found this post that explains the new structure for sector_alamr
> https://community.home-assistant.io/t/sector-alarm/24712/100
> 
> > 1. create new folder custom_components\sector_alarm
> > 2. Move custom_components\sector_alarm.py to custom_components\sector_alarm__init__.py
> > 3. Move custom_components\sensor\sector_alarm.py to custom_components\sector_alarm\sensor.py
> > 4. Move custom_components\alarm_control_panel\sector_alarm.py to custom_components\sector_alarm\alarm_control_panel.py
> 
> this works for me at least

This doesnt work for me, im getting:
`Setup failed for sector_alarm: Component failed to initialize.`

Nothing more info.. not sure what to do.. really want this to work..

**Comment by phellarv** [comment]
@mgejke Offline?

**Comment by mgejke** [comment]
Huh? The repo is updated with the new structure, replace the files in the custom_components-folder with the current ones from the repo.

**Comment by phellarv** [comment]
Oh - sorry. A bit triggerhappy here.
